apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-loadbalancer
  labels:
    name: mongo
  #annotations:
   # service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - port: 27017
    targetPort: 27017
  #clusterIP: None
  selector:
    role: mongo
  type: LoadBalancer