apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-deployment
spec:
  type: NodePort
  selector:
    matchLabels:
      app: echoserver
  replicas: 1
  template: # create pods using pod definition in this template
    metadata:  
      labels:
        app: echoserver
    spec:
      containers:
      - name: echoserver
        image: gcr.io/google_containers/echoserver:1.4
        ports:
        - containerPort: 8080
